language: r
cache: packages
branches:
  only:
  - master
r_github_packages:
    - rstudio/blogdown
before_script:
    - Rscript -e 'blogdown::install_hugo(version = "0.29")'
script:
    - Rscript -e 'blogdown::build_site()'
    - sh _build_and_merge.sh
    - touch public/.nojekyll
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master
  local_dir: public
  target_branch: gh-pages
notifications:
  slack:
    rooms:
      secure: Qe0ZJd5xykUAKgmEEgU+otFCD6tU58BgYo+1v2rw1LkJrHzOqgeYxxB28DNn/T7mdgTj/EYou5rTewyC7G2yiFMqJ5YRGxjR6PrIC7Uc3e/YqI9ZgGxkmQ51+PEmRjVyo8mZp6pNVPOjeiypM6XzFmo2P9TDZ7bXizJDtqbo9hBguZ9+hdpi4yaczMz4UyEqG38HC426V1bOjBb8dA6DIwg9LHM6gxh5AdpeCh/HZ21qFL2s/C60BipGBQOvae2buEoMzu5Q4fPKHlVkg42uJbvq1k6qKNqLOdcU9uFFzMsaf3PyLDHgYgOz9hbx+nU82RYXT88oVLRA8sh/k1A+mizo2jG5lhnRBsyfLHt3zpfhEzYU8AbPixIxTwALay8LgK4hjk3Om388n0JBlRSN46/l0OK8F6100vslKvAa3dzy64q5BmV/PHwJQth/I+2vO26DS/vcJxjhtKFAf1Kbooz/cleu0X4s5dtArk7tOR3BCIaN7Xjb0ZNaa7mg0bHrjv7BixcjH4x0n2WcVLmrUiBfOVKcdfBGuMbUfd9kp9peqIdgTzlGpqT8E0SYZ/GiIca+kKucsWcHw2VBz54GDTP85Aim9os2Jo8xCRrEF11kXlLTGeI2FPDa1an5JsO26KOAXuQL9DzBKIfgAdpRV7sfyvn9VFnZgP6h4wUdlR4=
