language: r
cache: packages
branches:
  only:
  - master
r_github_packages:
    - rstudio/blogdown
before_script:
    - Rscript -e 'blogdown::install_hugo(version = "0.29")'
script:
    - Rscript -e 'blogdown::build_site()'
    - sh _build_and_merge.sh
    - touch public/.nojekyll
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master
  local_dir: public
  target_branch: gh-pages
notifications:
  slack:
    rooms:
      secure: rp44VVJlavRGLw0Y4B5IcemLXu/YdVf5AQ8Pe+2v3+UCCW3Wd0uFftjKpxRcjU+ey9oSdoNkxOx6VGf84dpm7KMKjoqd36JIpSd4gzWu4eblMevjyI25TPPN5edXSTVyLoOV3S7dRYTObsivIxVLJzjsCs75rb1ouhd8yh8WeSjTNGRVVQmPmS3o5nwOgf6KJ1xc8V1DDCmVhATE3qZLPXx0U2twf/oILmssFAj+ibaS5ABYUNGEEqgSFoJnw0UnqPEM5FyOh0simnJK8L+HTyo92IAtxoloFBpc+3kFPGIRUXwVNV0H8Zm/pYm9xCGQohLSR66tDwUVD9pA5cAAlqGdnq7zg5N79NP5GtxkJ5ygLVR+ElHw2FBKUvG11EUe4Ji/13SjCVbksskcKXrNWkn0xh7dU49G3TPyzp2lqag6EDFgKdBpS9dLHiGpgz3SPYAAZtsXq78P0hgddZkGvUyHWGPjqbn0Vm42SQHReS+r0bLDEt8AaEqD32wwkCkNwsMb/mpNWsFzk+oPjnMgu4iVCTmUmJ/VJYf2icgRdrKdRTBxDmRN4WA/yJztXBK63g5tnAXINfxXm/w1vJ9OssirdaNHTpIxOp1FZowgbLzjo54Ye0PT/Ql6z3qDIWkBIbN1T+9D1ZYJymHXv/gQo2slCiYUmkYW4mLUuf4nPmc=
