---
time_slot: 10 minutes
---

# Continued Learning

Now that you've learned about reproducible data analysis in R, you'll want a list of references to look back on, some tips about where to find help, and some pointers on how to further develop your R skills. One of the great things about open source tools like R, is the abundance of free resources available to help you teach yourself.

## References

- The [materials](https://nceas.github.io/sasap-training/materials/) from this course
- RStudio built in documentation (help tab, .etc)
- [git-scm.com](git-scm.com) tutorials and documentation
- cheat-sheets (RStudio -> Help -> Cheatsheets)

## Where to Find Help

- [stackoverflow](https://stackoverflow.com/): a great set of websites for finding well vetted answers to specific problems.
- [The R Inferno](http://www.burns-stat.com/documents/books/the-r-inferno/)
- [aRrgh: a newcomer’s (angry) guide to R](http://arrgh.tim-smith.us/)

## Other helpful and/or cool stuff

- [Jupyter Lab](https://github.com/jupyterlab/jupyterlab): an alternative to RMarkdown that also works with Python and other programming languages. Part of [Project Jupyter](jupyter.org).

<!-- This is going to get too wordy. ...but maybe we want it in there at some point?
## Choosing Which Library to Use

Sometimes when you want to do something beyond what can be accomplished with the packages you know in R, you'll find that there are many competing packages the, at least preportedly, can do that thing. A reasonable first step is simply to do a Google search. Often this will turn up many different packages that do nearly the same thing. How do you decide which to use?

- Compatibility with other packages (e.g., the tidyverse)
- Under active development? Check activity in the package repo

For instance, you may want to work with spatial data (e.g., shapefiles) in R. blah blah blah. Go through how to decidebe between sp, sf, spatial, etc.
-->
